creation_rules:
  - path_regex: \.global\.yaml$
    #  aws kms key global region
    # aws iam user/terragrunt role have the kms key permission
    kms: 'arn:aws:kms:us-east-1:733051034790:key/mrk-xxxxxx'
#    aws_profile: terragrunt
    pgp: '01D0D800C76AC893E74990B44BB1CE513349E336'

    # aws china region
  - path_regex: \.china\.yaml$
#    aws_profile: wwc
    kms: 'arn:aws-cn:kms:cn-northwest-1:527109613237:key/d315eb9b-99a3-446b-b105-fd0126d10b0e'
    pgp: '01D0D800C76AC893E74990B44BB1CE513349E336'